// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6vYvDd_xDi9pxOIzL6BQNa_kd_F_frc',
    appId: '1:404804582377:web:c287ea8c5d985adc412978',
    messagingSenderId: '404804582377',
    projectId: 'pody-784db',
    authDomain: 'pody-784db.firebaseapp.com',
    storageBucket: 'pody-784db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJdZZM8Lj9p5eynKasuJuy3OKg1nX8NDE',
    appId: '1:404804582377:android:1214c395aabe3b99412978',
    messagingSenderId: '404804582377',
    projectId: 'pody-784db',
    storageBucket: 'pody-784db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSM1Jo8F_QurQTrz1o_ZKh7zCx1Pz4lYM',
    appId: '1:404804582377:ios:03ed894245c6d80d412978',
    messagingSenderId: '404804582377',
    projectId: 'pody-784db',
    storageBucket: 'pody-784db.appspot.com',
    iosClientId: '404804582377-oqjoqte60lja9jf582hs30f5d4islt1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.podcastApp',
  );
}
